from __future__ import annotations

from datetime import UTC, datetime
from pathlib import Path

from osx_system_agent.log import get_logger
from osx_system_agent.scanners.caches import scan_caches
from osx_system_agent.scanners.disk_hogs import scan_disk_hogs
from osx_system_agent.scanners.launch_agents import scan_launch_agents
from osx_system_agent.system.activity import get_system_status
from osx_system_agent.utils.human import bytes_to_human
from osx_system_agent.utils.paths import ensure_dir

log = get_logger("reports.markdown")


def generate_markdown_report(
    output_dir: Path,
    scan_path: Path | None = None,
) -> Path:
    """Generate a human-readable Markdown system health report."""
    timestamp = datetime.now(tz=UTC).isoformat(timespec="seconds")
    lines: list[str] = []

    lines.append("# macOS System Health Report")
    lines.append(f"\nGenerated: {timestamp}\n")

    # System status
    sys_status = get_system_status()
    disk_pct = (
        sys_status.disk_used / sys_status.disk_total * 100
        if sys_status.disk_total > 0 else 0
    )
    mem_pct = (
        sys_status.memory_used / sys_status.memory_total * 100
        if sys_status.memory_total > 0 else 0
    )

    lines.append("## System Overview\n")
    lines.append("| Metric | Value |")
    lines.append("|--------|-------|")
    lines.append(f"| CPU | {sys_status.cpu_percent:.1f}% |")
    lines.append(
        f"| Memory | {bytes_to_human(sys_status.memory_used)} / "
        f"{bytes_to_human(sys_status.memory_total)} ({mem_pct:.0f}%) |"
    )
    lines.append(
        f"| Disk | {bytes_to_human(sys_status.disk_used)} / "
        f"{bytes_to_human(sys_status.disk_total)} ({disk_pct:.0f}%) |"
    )
    lines.append(
        f"| Disk Free | {bytes_to_human(sys_status.disk_free)} |"
    )

    if sys_status.battery:
        bat = sys_status.battery
        plug = "Plugged" if bat.power_plugged else "Battery"
        pct = f"{bat.percent:.0f}%" if bat.percent is not None else "N/A"
        lines.append(f"| Battery | {pct} ({plug}) |")

    lines.append("")

    # Disk hogs
    hogs = scan_disk_hogs(min_size=500 * 1024 * 1024)  # 500MB+
    if hogs:
        lines.append("## Disk Hogs (>500MB)\n")
        lines.append("| Directory | Size | Files |")
        lines.append("|-----------|------|-------|")
        for d in hogs[:15]:
            lines.append(
                f"| `{d.path}` | {bytes_to_human(d.size)} "
                f"| {d.file_count} |"
            )
        lines.append("")

    # Caches
    caches = scan_caches(min_size=50 * 1024 * 1024)  # 50MB+
    if caches:
        total = sum(c.size for c in caches)
        lines.append(f"## Caches ({bytes_to_human(total)} total)\n")
        lines.append("| Category | Size | Files |")
        lines.append("|----------|------|-------|")
        for c in caches:
            lines.append(
                f"| {c.category} | {bytes_to_human(c.size)} "
                f"| {c.file_count} |"
            )
        lines.append("")

    # Launch agents
    agents = scan_launch_agents(include_apple=False)
    run_at_load = [a for a in agents if a.run_at_load and not a.disabled]
    if agents:
        lines.append(
            f"## Launch Agents ({len(agents)} total, "
            f"{len(run_at_load)} at boot)\n"
        )
        if run_at_load:
            lines.append("**Run at load:**\n")
            for a in run_at_load[:20]:
                lines.append(f"- `{a.label}` ({a.scope})")
            lines.append("")

    # Recommendations
    lines.append("## Recommendations\n")
    recs: list[str] = []

    if disk_pct > 80:
        recs.append(
            f"- **Disk space low** ({disk_pct:.0f}% used). "
            "Run `osa clean caches` and `osa scan disk-hogs`."
        )
    if caches and total > 5 * 1024**3:
        recs.append(
            f"- **Large caches** ({bytes_to_human(total)}). "
            "Run `osa clean caches --no-dry-run` to reclaim space."
        )
    if len(run_at_load) > 15:
        recs.append(
            f"- **{len(run_at_load)} agents at boot**. "
            "Review with `osa scan launch-agents` — "
            "disable unused ones for faster startup."
        )
    if not recs:
        recs.append("- System looks healthy. No urgent actions needed.")

    lines.extend(recs)
    lines.append("")

    lines.append("---")
    lines.append("*Generated by osx-system-agent*\n")

    # Write
    ensure_dir(output_dir)
    stamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    report_path = output_dir / f"system-report-{stamp}.md"
    report_path.write_text("\n".join(lines))

    log.info("markdown report written to %s", report_path)
    return report_path
